[build]
# Railway 빌드 설정
buildCommand = "echo 'Railway.toml 강제 적용'"

[deploy]
# Railway 배포 설정 - 강제 적용
startCommand = "cd /app/src && python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
# 환경변수 기본값
PORT = "8080"