[build]
# Railway 빌드 설정
buildCommand = "echo 'Railway 완벽 설정 적용'"

[deploy]
# Railway 완벽 배포 설정 - 환경변수 문제 해결
startCommand = "python railway_start.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
# 환경변수 기본값
PORT = "8080"