[build]
builder = "nixpacks"

[deploy]
startCommand = "python railway_safe_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app" 